/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ganqiang.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JobCommand implements org.apache.thrift.TEnum {
  PAUSE(0),
  CONTINUE(1),
  CANCEL(2);

  private final int value;

  private JobCommand(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobCommand findByValue(int value) { 
    switch (value) {
      case 0:
        return PAUSE;
      case 1:
        return CONTINUE;
      case 2:
        return CANCEL;
      default:
        return null;
    }
  }
}
